In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Read csv file
df = pd.read_csv('survey_data_updated.csv')
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [5]:
df.shape

(18845, 114)

In [6]:
# Prepare DataFrame only which columns required and check info
df_cleaned = df[['ResponseId', 'Age', 'EdLevel', 'Country', 'LanguageHaveWorkedWith',
          'DatabaseHaveWorkedWith', 'PlatformHaveWorkedWith',
          'WebframeHaveWorkedWith', 'LanguageWantToWorkWith',
          'DatabaseWantToWorkWith', 'PlatformWantToWorkWith',
          'WebframeWantToWorkWith']].copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18845 entries, 0 to 18844
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ResponseId              18845 non-null  int64
 1   Age                     18845 non-null  object
 2   EdLevel                 18845 non-null  object
 3   Country                 18845 non-null  object
 4   LanguageHaveWorkedWith  18845 non-null  object
 5   DatabaseHaveWorkedWith  18845 non-null  object
 6   PlatformHaveWorkedWith  18845 non-null  object
 7   WebframeHaveWorkedWith  18845 non-null  object
 8   LanguageWantToWorkWith  18845 non-null  object
 9   DatabaseWantToWorkWith  18845 non-null  object
 10  PlatformWantToWorkWith  18845 non-null  object
 11  WebframeWantToWorkWith  18845 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.7+ MB

In [7]:
df_cleaned.head()

,ResponseId,Age,EdLevel,Country,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,PlatformHaveWorkedWith,WebframeHaveWorkedWith,LanguageWantToWorkWith,DatabaseWantToWorkWith,PlatformWantToWorkWith,WebframeWantToWorkWith
0,2,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United Kingdom of Great Britain and Northern I...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Express;Htmx;Node.js;React;Remix
1,3,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",United Kingdom of Great Britain and Northern I...,C#,Firebase Realtime Database,Google Cloud,ASP.NET CORE,C#,Firebase Realtime Database,Google Cloud,ASP.NET CORE
2,10,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Serbia,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React
3,11,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",United States of America,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Node.js;React;Ruby on Rails,C#;Crystal;Java;JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Google Cloud,Django;Node.js;React;Ruby on Rails
4,12,45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Poland,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Power...,Microsoft Access;Microsoft SQL Server;PostgreS...,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,C#;HTML/CSS;JavaScript;PowerShell;Rust;SQL;Typ...,Microsoft SQL Server;PostgreSQL;SQLite,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React

In [8]:
# Check Age column
df_cleaned['Age'].unique()

array(['35-44 years old', '45-54 years old', '25-34 years old',
       '55-64 years old', '18-24 years old', 'Under 18 years old',
       '65 years or older', 'Prefer not to say'], dtype=object)

In [9]:
# Check Age column
df_cleaned['EdLevel'].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)', 'Something else',
       'Primary/elementary school'], dtype=object)

In [10]:
# Map messy education levels to simplified categories
edlevel_mapping = {
    "Bachelor's degree (B.A., B.S., B.Eng., etc.)": "Bachelor",
    "Master's degree (M.A., M.S., M.Eng., MBA, etc.)": "Master",
    "Professional degree (JD, MD, Ph.D, Ed.D, etc.)": "Doctorate",
    "Associate degree (A.A., A.S., etc.)": "Associate",
    "Some college/university study without earning a degree": "Some College",
    "Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)": "Secondary School",
    "Primary/elementary school": "Primary School",
    "Something else": "Other"
}

df_cleaned['EdLevel'] = df_cleaned['EdLevel'].map(edlevel_mapping)
display(df_cleaned['EdLevel'].unique())

array([nan, 'Doctorate', 'Some College', 'Secondary School', 'Associate',
       'Other', 'Primary School'], dtype=object)

In [11]:
# Check Country column
df_cleaned['Country'].unique()

array(['United Kingdom of Great Britain and Northern Ireland', 'Serbia',
       'United States of America', 'Poland', 'Germany', 'Ireland',
       'Italy', 'Philippines', 'Brazil', 'Austria', 'France', 'Romania',
       'Switzerland', 'Sweden', 'Republic of North Macedonia', 'Greece',
       'United Republic of Tanzania', 'Japan', 'India', 'Argentina',
       'Pakistan', 'Croatia', 'Turkey', 'Portugal', 'Sri Lanka',
       'Hungary', 'Canada', 'Czech Republic', 'Bulgaria', 'Netherlands',
       'Dominican Republic', 'Morocco', 'Russian Federation', 'Tunisia',
       'Bangladesh', 'Ukraine', 'Viet Nam', 'Belgium', 'Spain',
       'South Africa', 'Chile', 'Ghana', 'Israel', 'Bolivia',
       'Luxembourg', 'Georgia', 'Saudi Arabia', 'Algeria', 'Lithuania',
       'Kazakhstan', 'Jordan', 'Venezuela, Bolivarian Republic of...',
       'Denmark', 'Nicaragua', 'Thailand', 'Indonesia', 'Mexico',
       'Slovakia', 'El Salvador', 'Latvia', 'Peru', 'Malaysia', 'Finland',
       'Zimbabwe', 'Malta', 'Uruguay', 'Nigeria', 'Colombia', 'Egypt',
       'Albania', 'Afghanistan', 'Slovenia', 'Palestine', 'Ecuador',
       'Paraguay', 'Ethiopia', 'New Zealand', 'Guatemala',
       'Bosnia and Herzegovina', 'Norway', 'Costa Rica', 'Australia',
       'Kenya', 'Armenia', 'Estonia', 'Iceland', 'Honduras',
       'Hong Kong (S.A.R.)', 'South Korea', 'United Arab Emirates',
       'China', 'Mongolia', 'Singapore', 'Cambodia',
       'Iran, Islamic Republic of...', 'Nepal', 'Uzbekistan', 'Taiwan',
       'Montenegro', 'Lebanon', 'Benin',
       'Democratic Republic of the Congo', 'Belarus', 'Republic of Korea',
       'Cyprus', 'Tajikistan', 'Isle of Man', 'Rwanda', 'Sierra Leone',
       'Panama', 'Cuba', 'Kyrgyzstan', 'Syrian Arab Republic', 'Zambia',
       'Togo', 'Oman', 'Uganda', 'Nomadic', 'Andorra', 'Turkmenistan',
       'Qatar', 'Mauritius', 'Namibia', 'Kosovo', 'Angola',
       "Côte d'Ivoire", 'Malawi', 'Republic of Moldova', 'Iraq',
       'Madagascar', 'Sudan', 'Cameroon', 'Azerbaijan',
       'Central African Republic', 'Myanmar', 'Somalia', 'Suriname',
       'Belize', 'Kuwait', 'Congo, Republic of the...', 'Burkina Faso',
       'Bahrain', 'Yemen', 'Niger', 'Jamaica', 'Mauritania', 'Fiji',
       'Mozambique', 'Antigua and Barbuda', 'Senegal',
       'Trinidad and Tobago', 'Samoa', 'Bhutan', 'Brunei Darussalam',
       'Burundi', 'Guyana', 'Maldives', 'Monaco', 'Mali', 'Cape Verde',
       'Barbados'], dtype=object)

In [12]:
# Standardized Country name
country_mapping = {
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'United States of America': 'United States',
    'Republic of North Macedonia': 'North Macedonia',
    'Russian Federation': 'Russia',
    'United Republic of Tanzania': 'Tanzania',
    'Iran, Islamic Republic of...': 'Iran',
    'Venezuela, Bolivarian Republic of...': 'Venezuela',
    'Hong Kong (S.A.R.)': 'Hong Kong',
    'Democratic Republic of the Congo': 'DR Congo',
    'Congo, Republic of the...': 'Congo (Republic)',
    'Viet Nam': 'Vietnam',
    'Republic of Korea': 'South Korea',
    'Syrian Arab Republic': 'Syria'
}

df_cleaned['Country'] = df_cleaned['Country'].replace(country_mapping)
display(df_cleaned['Country'].unique())

array(['United Kingdom', 'Serbia', 'United States', 'Poland', 'Germany',
       'Ireland', 'Italy', 'Philippines', 'Brazil', 'Austria', 'France',
       'Romania', 'Switzerland', 'Sweden', 'North Macedonia', 'Greece',
       'Tanzania', 'Japan', 'India', 'Argentina', 'Pakistan', 'Croatia',
       'Turkey', 'Portugal', 'Sri Lanka', 'Hungary', 'Canada',
       'Czech Republic', 'Bulgaria', 'Netherlands', 'Dominican Republic',
       'Morocco', 'Russia', 'Tunisia', 'Bangladesh', 'Ukraine', 'Vietnam',
       'Belgium', 'Spain', 'South Africa', 'Chile', 'Ghana', 'Israel',
       'Bolivia', 'Luxembourg', 'Georgia', 'Saudi Arabia', 'Algeria',
       'Lithuania', 'Kazakhstan', 'Jordan', 'Venezuela', 'Denmark',
       'Nicaragua', 'Thailand', 'Indonesia', 'Mexico', 'Slovakia',
       'El Salvador', 'Latvia', 'Peru', 'Malaysia', 'Finland', 'Zimbabwe',
       'Malta', 'Uruguay', 'Nigeria', 'Colombia', 'Egypt', 'Albania',
       'Afghanistan', 'Slovenia', 'Palestine', 'Ecuador', 'Paraguay',
       'Ethiopia', 'New Zealand', 'Guatemala', 'Bosnia and Herzegovina',
       'Norway', 'Costa Rica', 'Australia', 'Kenya', 'Armenia', 'Estonia',
       'Iceland', 'Honduras', 'Hong Kong', 'South Korea',
       'United Arab Emirates', 'China', 'Mongolia', 'Singapore',
       'Cambodia', 'Iran', 'Nepal', 'Uzbekistan', 'Taiwan', 'Montenegro',
       'Lebanon', 'Benin', 'DR Congo', 'Belarus', 'Cyprus', 'Tajikistan',
       'Isle of Man', 'Rwanda', 'Sierra Leone', 'Panama', 'Cuba',
       'Kyrgyzstan', 'Syria', 'Zambia', 'Togo', 'Oman', 'Uganda',
       'Nomadic', 'Andorra', 'Turkmenistan', 'Qatar', 'Mauritius',
       'Namibia', 'Kosovo', 'Angola', "Côte d'Ivoire", 'Malawi',
       'Republic of Moldova', 'Iraq', 'Madagascar', 'Sudan', 'Cameroon',
       'Azerbaijan', 'Central African Republic', 'Myanmar', 'Somalia',
       'Suriname', 'Belize', 'Kuwait', 'Congo (Republic)', 'Burkina Faso',
       'Bahrain', 'Yemen', 'Niger', 'Jamaica', 'Mauritania', 'Fiji',
       'Mozambique', 'Antigua and Barbuda', 'Senegal',
       'Trinidad and Tobago', 'Samoa', 'Bhutan', 'Brunei Darussalam',
       'Burundi', 'Guyana', 'Maldives', 'Monaco', 'Mali', 'Cape Verde',
       'Barbados'], dtype=object)

In [13]:
# Define multi-item columns
multi_item_columns = [
    'LanguageHaveWorkedWith',
    'DatabaseHaveWorkedWith',
    'PlatformHaveWorkedWith',
    'WebframeHaveWorkedWith',
    'LanguageWantToWorkWith',
    'DatabaseWantToWorkWith',
    'PlatformWantToWorkWith',
    'WebframeWantToWorkWith'
]

In [14]:
# Create reusable normalize function
def normalize_multivalue_column(df, column_name, id_col='ResponseId'):
    """
    Splits a semicolon-separated column into one row per value.
    """
    temp = df[[id_col, column_name]].dropna().copy()
    temp[column_name] = temp[column_name].str.split(';')
    temp = temp.explode(column_name)
    temp[column_name] = temp[column_name].str.strip()
    temp = temp[temp[column_name] != '']  # remove empty values
    return temp

In [15]:
# Normalize all multi-item columns
normalized_tables = {}

for col in multi_item_columns:
    normalized_tables[col] = normalize_multivalue_column(df_cleaned, col)

In [16]:
# Export all columns to csv file
for col, df_norm in normalized_tables.items():
    output_name = f"survey_{col.lower()}_normalized.csv"
    df_norm.to_csv(output_name, index=False)
    print(f"Saved: {output_name}")

Saved: survey_languagehaveworkedwith_normalized.csv
Saved: survey_databasehaveworkedwith_normalized.csv
Saved: survey_platformhaveworkedwith_normalized.csv
Saved: survey_webframehaveworkedwith_normalized.csv
Saved: survey_languagewanttoworkwith_normalized.csv
Saved: survey_databasewanttoworkwith_normalized.csv
Saved: survey_platformwanttoworkwith_normalized.csv
Saved: survey_webframewanttoworkwith_normalized.csv

In [17]:
# Export all demographic columns to csv file
demographic_columns = ['ResponseId', 'Age', 'EdLevel', 'Country']
df_demographics = df_cleaned[demographic_columns].copy()
df_demographics.to_csv('survey_demographics.csv', index=False)